name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.8'

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest ruff

    - name: Run tests
      env:
        FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
      run: |
        pytest

    - name: Run Ruff
      run: |
        ruff check .
      continue-on-error: true

    - name: Run Ruff format
      run: |
        ruff format --check .
      continue-on-error: true

    - name: Check PEP8 compliance
      run: |
        ruff check --select E,F,W,I,N .
      continue-on-error: true
