name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest ruff
    - name: Run tests
      env:
        FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
      run: |
        pytest
    - name: Run Ruff (with warnings)
      continue-on-error: true
      run: |
        ruff_output=$(ruff . 2>&1)
        echo "Ruff output:"
        echo "$ruff_output"
        echo "::warning ::Ruff found linting issues. See output above for details."
    - name: Check PEP8 compliance (with warnings)
      continue-on-error: true
      run: |
        pep8_output=$(ruff check --select E,F,W,I,N . 2>&1)
        echo "PEP8 check output:"
        echo "$pep8_output"
        echo "::warning ::PEP8 check found style issues. See output above for details."
